# This rule is not used by the project garage-s3-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to garage.s3operator.fr resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: garage-s3-operator
    app.kubernetes.io/managed-by: kustomize
  name: garages3instance-viewer-role
rules:
- apiGroups:
  - garage.s3operator.fr
  resources:
  - garages3instances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - garage.s3operator.fr
  resources:
  - garages3instances/status
  verbs:
  - get
