apiVersion: garage.s3operator.fr/v1alpha1
kind: GarageS3Instance
metadata:
  name: garage
  namespace: test-s3operator
spec:
  url: "http://garage.garage.svc.cluster.local"
  port: 3903
  adminTokenSecret: garage-admin-token
---
apiVersion: v1
kind: Secret
metadata:
  name: garage-admin-token
  namespace: test-s3operator
type: Opaque
stringData:
  token: "mySecretAdminToken"