---
# Source: garage/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: garage
---
# Source: garage/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manage-crds-default-garage
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch", "create", "patch"]
- apiGroups: ["deuxfleurs.fr"]
  resources: ["garagenodes"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
# Source: garage/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: allow-crds-for-default-garage
subjects:
- kind: ServiceAccount
  name: garage
  namespace: default
roleRef:
  kind: ClusterRole
  name: manage-crds-default-garage
  apiGroup: rbac.authorization.k8s.io